------------------ Data for `content` table -------------------

INSERT INTO `content`(`title`, `description`, `content`) 
VALUES 
-- HOME PAGE --
("Choosing the best foods","","In order to choose the best foods for hiking, you need to strike the right balance. Ideally, you should eat foods that are tasty and packed with nutrients, but they should also be light and portable. In contrast to running and cycling, you don't just consider fuelling your effort. If you plan on hiking for a few days, you may need to consider lunches and even post-hike dinners while you're still in the wilderness.<br><br>It doesn't have to be complicated to devise the optimal fuelling strategy, and Hike Foodie can help. Natural nutrition is all we do, so we're here with hiking food ideas based on our expertise. You will also learn how to prepare healthy, delicious fuel for your walks."),
("The right calories","","To avoid weight loss and keep up your energy levels, you need to eat the right amount of calories while hiking. Hiking burns around 3500 calories each day on average. However, the amount of calories burned by an individual depends on their weight. Weight is generally a determinant of how many calories you burn. An individual weighing 70 kg might burn around 440 calories per hour hiking, while an individual weighing 90 kg might burn up to 550 calories per hour.<br><br>Therefore, you should make sure to eat enough food for your hike in order to burn enough calories. Experts recommend consuming 2000 calories for easy hikes and over 4,500 calories for severe terrain and cold weather trips. This is because the number of calories you burn can vary depending on your location and environment. For example, trekking on flat, rocky terrain burns more calories than hiking on flat, grassy terrain. Using a heavy pack will increase the amount of calories burned. The more difficult the hike, the more calories you'll burn, so plan your route and the circumstances you'll experience ahead of time."),
("The right nutrition","","While it's always vital to eat well, the most important thing to remember when hiking is to keep your energy levels up. So, in addition to protein, carbs should play a significant role in your diet. A mixture of basic and complex carbs should be included in your diet. Simple carbohydrates might provide an immediate energy boost. Natural foods, such as fruits and milk, as well as processed refined sugars, such as sweets, syrups, and soft drinks, contain them. Complex carbohydrates give a slower and more sustained flow of energy because they take longer to breakdown. They can be found in bread, rice, and pasta, among other things.<br><br>It's best to mix these two carbohydrates together so that you get a sustained energy release during your hike as well as fast spurts of energy throughout the day. For example, you may start your day with complex carbs, such as a bowl of porridge, and then snack on simple carbs, such as raisins, dried fruits, and energy bars, throughout the day. You might end the day with a complex carb meal, such as chicken with pasta or rice, in addition to refuelling at lunch.<br><br>Fats, in addition to protein and carbohydrates, are a good supplement to your journey because they are high in energy and calorie density. They have roughly nine calories per gramme, as opposed to four calories per gramme for protein and carbs. It's better to eat foods that are high in healthy fats, such as almonds, which are great for snacking on while hiking. Foods with a high fibre content are also worth considering because they help you feel fuller for longer."),
("When and how often to eat","","It's not just about what you eat on a trek, but also when you eat. To stay energised during the day, you should eat on a regular basis. This is especially true if you're eating simple carbohydrates, which provide short spurts of energy that quickly wear off. It's a good idea to aim to eat every two hours to gently and consistently drip carbs into your system, preventing energy spikes and troughs.<br><br>You should have a large breakfast before starting your hike and refill within one hour of ending. It's also a good idea to eat about half an hour before bedtime to try to replenish the energy you expended on your journey, especially if you plan on hiking the next day."),
-- BREAKFAST --
("Avocado sandwich variations","","<h2>You'll need:</h2><ul><li>1 ripe avocado</li><li>1 large egg</li><li>1 tomato</li><li>3 slices of your favourite bread</li><li>40g Feta cheese, crumbled</li><li>1tsp of cooking oil</li><li>Pepper</li><li>Salt</li></ul><h2>At home:</h2><ul><li>Pack all the ingredients separately.</li></ul><h2>On the trail:</h2><ul><li>Heat a pan over medium heat. Toast bread in a pan without oil</li><li>Cut the avocado in 2, remove the stone and scoop out the flesh into a plate. Mash with a fork. Spread on the bread.</li><li>Toast variation No. 1: Crumble the Feta cheese over the avocado</li><li>Toast variation No. 2: add slices of tomato</li><li>Toast variation No. 3: add fried egg on top</li></ul>"),
("Tropical oatmeal","","<h2>You'll need:</h2><ul><li>30g cup quick cooking oats</li><li>boiling water</li><li>2 tablespoons powdered milk</li><li>1 teaspoon of sugar</li><li>10g dried coconut flakes</li><li>1 Passion fruit</li><li>1 Apple</li><li>10g Almonds</li><li>2 Tbsp Honey</li><li>Salt</li></ul><h2>At home:</h2><ul><li>Mix oats, powdered milk, sugar, coconut flakes, almonds and salt in a zip lock bag.</li></ul><h2>On the trail:</h2><ul><li>Bring 20ml to 120ml of water to a boil, pour all the ingredients from zip lock bag, stir, and let stand for 5 minutes. Add sliced apple and passion fruit</li></ul>"),
-- SNACKS --
("Cheese and Meat Platter","","<h2>You'll need:</h2><ul><li>Dry salami</li><li>Prosciutto</li><li>Low moisture, semi-firm/firm cheese: cheddar, aged Gouda, Manchego, Emmental, Gruyere</li><li>Olives</li><li>Sundried tomatoes</li><li>Cherry tomatoes</li></ul><h2>At home:</h2><ul><li>Pack all the ingredients separately</li></ul><h2>On the trail:</h2><ul><li>Arrange all ingredients on a plate</li>               </ul>"),
("Chocolate Cherry Trail Mix","","<h2>You'll need:</h2><ul><li>Walnuts</li><li>Dried cherries (or dried cranberries)</li><li>Dark chocolate chunks and/or cacao nibs</li><li>Pumpkin seeds</li><li>Dried blueberies</li></ul><h2>At home:</h2><ul><li>Mix walnuts, dried cherries, dark chocolate chunks/cacao nibs, pumpkin seeds, dried blueberies into a large mixing bowl.</li><li>Stir ingredients so they are evenly distributed.</li><li>Equally divide into plastic bags for easy distribution.</li></ul><h2>On the trail:</h2><ul><li>Enjoy on the go</li></ul>"),
-- STOVELESS MEALS --
("Guacamole bruschetta","","<h2>You'll need:</h2><ul><li>1/2 loaf French bread</li><li>2 tablespoons olive oil</li><li>2 ripe avocados</li><li>1 Tomato</li><li>1 Lime</li><li>1 Small red onion</li><li>Black pepper</li><li>Dried Chile pepper</li><li>Sesame seeds</li><li>Salt</li></ul><h2>At home:</h2><ul><li>Pack all the ingredients separately.</li></ul><h2>On the trail:</h2><ul><li>Heat up the olive oil in a pan, lightly toast the bread for a minute each side.</li><li>Remove the bread from the pan and set aside</li><li>Cut the avocado in 2, remove the stone and scoop out the flesh into a bowl. Mash with a fork</li><li>Add tomato, red onion, lime juice, black pepper, salt, and mix until well combined</li><li>Spoon a portion of the mixture onto each of bruschetta and sprinkle dried Chile pepper and sesame seeds on top.</li></ul>"),
("Roast beef sandwich","","<h2>You'll need:</h2><ul><li>2 Roast beef slices</li><li>50g Spinach</li><li>2 slices of seeded bread</li><li>2 slices of Cheddar cheese</li><li>15g Sun dried tomato pesto</li><li>1 small carrot, peeled and grated</li><li>Salt</li></ul><h2>At home:</h2><ul><li>Spread pesto on the slice of bread</li><li>Top with roast beef slice</li><li>Top with shredded carrot</li><li>Top with spinach</li><li>Top with Cheddar cheese</li><li>Top with another slice of bread</li><li>Cut sandwich diagonally</li></ul><h2>On the trail:</h2><ul><li>Ready to eat</li></ul>"),
-- DESSERT --
("Chia pudding","","<h2>You'll need:</h2><ul><li>2 Tbsp Chia seeds</li><li>120ml Almond milk</li><li>Berries or fruit of your choice</li><li>Honey sachet or a sweetener</li></ul><h2>At home:</h2><ul>                 <li>Pack all the ingredients separately</li></ul><h2>On the trail:</h2><ul><li>Mix chia seeds with milk very well, then wait for a few minutes for chia pudding to settle and mix again. Add honey or a sweetener for sweetness. Let rest for at least 20 minutes. Mix and add berries or fruits of your choice.</li></ul>"),
("Peanut butter energy balls","","<h2>You'll need:</h2><ul><li>150g Honey</li><li>250g Peanut butter</li><li>300g Rolled oats</li><li>40g Chocolate chips</li><li>40g Shredded coconut</li></ul><h2>At home:</h2><ul><li>Combine all the ingredients in a bowl and stir well. Using a 1-tablespoon measure, roll the mixture into balls. Store in an airtight container for up to 5 days in the refrigerator or up to 3 months in the freezer.</li></ul><h2>On the trail:</h2><ul><li>Ready to eat.</li></ul>"),
("Chocolate protein cookies","","<h2>You'll need:</h2><ul><li>60g chocolate whey protein powder</li><li>250g drippy peanut butter</li><li>1 Tbsp Stevia</li><li>2 Tbsp unsweetened cocoa powder</li><li>2 large eggs</li><li>Coconut oil</li></ul><h2>At home:</h2><ul><li>Preheat the oven to 180ºC and spray a baking sheet with coconut oil cooking spray. Mix all the ingredients. The consistency should be similar to cookie dough. It should NOT be crumbly and if it is, this is a sign your peanut butter is not drippy enough and we recommend adding 1-2 teaspoons of melted coconut oil.<br>Spoon out 2 tablespoons of dough into your palms and roll into a ball. Flatten cookie dough between your palms creating a cookie shape and place it on a baking sheet. Note that your cookies won't expand a lot, so flattening is important.<br>Bake cookies at 180ºC for 10-12 minutes.<br>Let cool for 15 minutes before removing from the pan so that the protein cookies can set. If you remove them too soon, they may break in half.</li></ul><h2>On the trail:</h2><ul><li>Ready to eat.</li></ul>"),
-- DRINKS --
("Cold coffee","","<h2>You'll need:</h2><ul><li>300ml Water</li><li>30g Dry Milk Powder</li><li>1.5 tablespoon of Nescafe Instant Coffee</li><li>Sugar or sweetener</li></ul><h2>At home:</h2><ul><li>Combine all dry ingredients together and store in a baggie or a container.</li></ul><h2>On the trail:</h2><ul><li>Add approximately 300ml of water to a water bottle and add powder mixture. Shake or stir vigorously to combine.</li></ul>"),
("Strawberry smoothie","","<h2>You'll need:</h2><ul><li>20g egg white powder</li><li>1 peanut butter sachet</li><li>20g cup freeze-dried and  ground strawberries</li><li>1 Strawberry Clif Shot gel</li></ul>               <h2>At home:</h2><ul><li>Pack all the ingredients separately.</li></ul><h2>On the trail:</h2><ul><li>Knead nut butter packets so they are fully blended and soft. Drop your ball whisk into a wide-mouth bottle, then add 200ml of water and all ingredients. Close lid and shake for a minute, until lumps are gone. Add another 200ml of water and shake again until fully blended.</li></ul>"),
("Cold brew tea","","<h2>You'll need:</h2><ul><li>Hibiscus/Green/White tea</li><li>300ml of water</li><li>Sugar or sweetener</li></ul><h2>At home:</h2><ul><li>Pack all the ingredients separately.</li></ul><h2>On the trail:</h2><ul><li>Add approximately 300ml of water and your chosen tea to a mason jar and leave it overnight. Enjoy in the morning.</li></ul>");
-- DINNER --
-- LUNCH --
-- STOVE COOKED MEALS --


-- ("","","")

