CREATE TABLE users (
	Id 			MEDIUMINT NOT NULL AUTO_INCREMENT,
	Name		VARCHAR(100) NULL,
	Surname		VARCHAR(100) NULL,
	Username	VARCHAR(100) NULL,
	Email		VARCHAR(100) NULL,
	Created		DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Id)
);
